# Effective Dart rules
# https://www.dartlang.org/guides/language/effective-dart
# https://github.com/dart-lang/linter/blob/master/example/effective-dart.yaml

linter:
  rules:
    - prefer_single_quotes
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments
    - package_api_docs
    - comment_references
    - implementation_imports
    - avoid_relative_lib_imports
    - prefer_adjacent_string_concatenation
    - prefer_interpolation_to_compose_strings
    - unnecessary_brace_in_string_interps
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - prefer_iterable_whereType
    - prefer_function_declarations_over_variables
    - unnecessary_lambdas
    - prefer_equal_for_default_values
    - avoid_init_to_null
    - unnecessary_getters_setters
    - prefer_final_fields
    - unnecessary_this
    - prefer_typing_uninitialized_variables
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - unnecessary_new
    - unnecessary_const
    - avoid_catches_without_on_clauses
    - use_rethrow_when_possible
    - use_to_and_as_if_applicable
    - one_member_abstracts
    - avoid_classes_with_only_static_members
    - prefer_constructors_over_static_methods
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_null
    - avoid_returning_this
    - type_annotate_public_apis
    - omit_local_variable_types
    - avoid_types_on_closure_parameters
    - avoid_return_types_on_setters
    - prefer_generic_function_type_aliases
    - avoid_private_typedef_functions
    - avoid_positional_boolean_parameters
    - hash_and_equals
    - avoid_null_checks_in_equality_operators
